# USER schema

# --- !Ups
create table USER (
  EMAIL VARCHAR(255) PRIMARY KEY,
  PSWDHASH INT NOT NULL,
  ROLE VARCHAR(10) NOT NULL,
  CREATED TIMESTAMP NOT NULL,
  TITLE VARCHAR(4),
  FIRST_NAME VARCHAR(255),
  MIDDLE_NAME VARCHAR(255),
  LAST_NAME VARCHAR(255),
  DOB DATE,
  NIN VARCHAR(9)
  );

create table CONTACT(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  UID BIGINT,
  CREATED TIMESTAMP NOT NULL,
  TITLE VARCHAR(5),
  FIRST_NAME VARCHAR(255),
  MIDDLE_NAME VARCHAR(255),
  LAST_NAME VARCHAR(255),
  DOB DATE,
  NIN VARCHAR(9)
  );

create table ADDRESS(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  LINE1 VARCHAR(255),
  LINE2 VARCHAR(255),
  LINE3 VARCHAR(255),
  CITY VARCHAR(50),
  COUNTY VARCHAR(50),
  POSTCODE VARCHAR(20),
  CREATED TIMESTAMP
);

create table USER_ADDRESS(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  EMAIL VARCHAR(255),
  ADD_ID BIGINT,
  CONSTRAINT FOREIGN KEY(EMAIL) REFERENCES USER(EMAIL),
  CONSTRAINT FOREIGN KEY (ADD_ID) REFERENCES ADDRESS(ID)
);

# --- !Downs
drop table USER;
drop table CONTACT;
drop table ADDRESS;