# USER schema

# --- !Ups
create table USER (
  EMAIL VARCHAR(255) PRIMARY KEY,
  PSWDHASH INT NOT NULL,
  ROLE VARCHAR(10) NOT NULL,
  CREATED TIMESTAMP NOT NULL,
  TITLE VARCHAR(4),
  FIRST_NAME VARCHAR(255),
  MIDDLE_NAME VARCHAR(255),
  LAST_NAME VARCHAR(255),
  DOB DATE,
  NIN VARCHAR(9)
  );

create table CONTACT(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  UID BIGINT,
  CREATED TIMESTAMP NOT NULL,
  TITLE VARCHAR(5),
  FIRST_NAME VARCHAR(255),
  MIDDLE_NAME VARCHAR(255),
  LAST_NAME VARCHAR(255),
  DOB DATE,
  NIN VARCHAR(9)
  );

create table ADDRESS(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  LINE1 VARCHAR(255),
  LINE2 VARCHAR(255),
  LINE3 VARCHAR(255),
  CITY VARCHAR(50),
  COUNTY VARCHAR(50),
  POSTCODE VARCHAR(20),
  CREATED TIMESTAMP
);

create table USER_ADDRESS(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  EMAIL VARCHAR(255),
  ADD_ID BIGINT,
  CONSTRAINT FOREIGN KEY(EMAIL) REFERENCES USER(EMAIL),
  CONSTRAINT FOREIGN KEY (ADD_ID) REFERENCES ADDRESS(ID)
);

create table COMPANY(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  TRADING_DATE DATE,
  SECTOR VARCHAR(255),
  FT_JOBS DECIMAL,
  PT_JOBS DECIMAL,
  LEGAL_FORM VARCHAR(255),
  URL VARCHAR(255),
  CREATED TIMESTAMP
);

create table USER_COMPANY(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  EMAIL VARCHAR(255),
  CID BIGINT,
  CREATED TIMESTAMP,
  CONSTRAINT FOREIGN KEY(EMAIL) REFERENCES USER(EMAIL),
  CONSTRAINT FOREIGN KEY(CID) REFERENCES COMPANY(ID)
);

create table COMPANY_ADDRESS(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  CID BIGINT,
  AID BIGINT,
  CONSTRAINT FOREIGN KEY (CID) REFERENCES COMPANY(ID),
  CONSTRAINT FOREIGN KEY (AID) REFERENCES ADDRESS(ID)
);

create table LOAN_APPLICATION(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  USERCO_ID BIGINT,
  AMOUNT DECIMAL NOT NULL,
  TERM INTEGER NOT NULL,
  JOBS_CREATED DECIMAL,
  LOAN_PURPOSE VARCHAR(30) NOT NULL,
  CREATED TIMESTAMP NULL,
  REVIEWED TIMESTAMP NULL,
  REVIEWED_BY VARCHAR(255),
  COMMENTS VARCHAR(255),
  ACCEPTED BOOLEAN,
  OFFER_APR DECIMAL(10,4),
  OFFER_DATE TIMESTAMP NULL,
  OFFER_ACCEPTED TIMESTAMP NULL,
  STATUS VARCHAR(15) NOT NULL,
  CONSTRAINT FOREIGN KEY (USERCO_ID) REFERENCES USER_COMPANY(ID)
);

create table JOURNAL_ENTRY (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  CREATED TIMESTAMP NOT NULL,
  ENTRY_DATE DATE NOT NULL
);




create table ACCOUNT (
  ID INT PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  AC_GROUP VARCHAR(50) NOT NULL
);



create table JOURNAL_LINE (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  JE_ID BIGINT NOT NULL,
  A_ID INT NOT NULL,
  AMOUNT DECIMAL(10,2) NOT NULL,
  MEMO VARCHAR(50),
  LA_ID BIGINT,
  CONSTRAINT FOREIGN KEY (JE_ID) REFERENCES JOURNAL_ENTRY (ID),
  CONSTRAINT FOREIGN KEY (A_ID) REFERENCES ACCOUNT (ID),
  CONSTRAINT FOREIGN KEY (LA_ID) REFERENCES LOAN_APPLICATION (ID)
);



# --- !Downs
drop table USER;
drop table CONTACT;
drop table ADDRESS;
drop table USER_ADDRESS;
drop table COMPANY;
drop table USER_COMPANY;
drop table COMPANY_ADDRESS;
drop table LOAN_APPLICATION;
drop table JOURNAL_ENTRY;
drop table ACCOUNT;
drop table JOURNAL_LINE;