# USER schema

# --- !Ups
create table USER (
  EMAIL VARCHAR(255) PRIMARY KEY,
  PSWDHASH INT NOT NULL,
  ROLE VARCHAR(10) NOT NULL,
  CREATED TIMESTAMP NOT NULL,
  TITLE VARCHAR(4),
  FIRST_NAME VARCHAR(255),
  MIDDLE_NAME VARCHAR(255),
  LAST_NAME VARCHAR(255),
  DOB DATE,
  NIN VARCHAR(9)
  );

create table CONTACT(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  UID BIGINT,
  CREATED TIMESTAMP NOT NULL,
  TITLE VARCHAR(5),
  FIRST_NAME VARCHAR(255),
  MIDDLE_NAME VARCHAR(255),
  LAST_NAME VARCHAR(255),
  DOB DATE,
  NIN VARCHAR(9)
  );

create table ADDRESS(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  LINE1 VARCHAR(255),
  LINE2 VARCHAR(255),
  LINE3 VARCHAR(255),
  CITY VARCHAR(50),
  COUNTY VARCHAR(50),
  POSTCODE VARCHAR(20),
  CREATED TIMESTAMP
);

create table USER_ADDRESS(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  EMAIL VARCHAR(255),
  ADD_ID BIGINT,
  CONSTRAINT FOREIGN KEY(EMAIL) REFERENCES USER(EMAIL),
  CONSTRAINT FOREIGN KEY (ADD_ID) REFERENCES ADDRESS(ID)
);

create table COMPANY(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  TRADING_DATE DATE,
  SECTOR VARCHAR(255),
  FT_JOBS DECIMAL,
  PT_JOBS DECIMAL,
  LEGAL_FORM VARCHAR(255),
  URL VARCHAR(255),
  CREATED TIMESTAMP
);

create table USER_COMPANY(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  EMAIL VARCHAR(255),
  CID BIGINT,
  CREATED TIMESTAMP,
  CONSTRAINT FOREIGN KEY(EMAIL) REFERENCES USER(EMAIL),
  CONSTRAINT FOREIGN KEY(CID) REFERENCES COMPANY(ID)
);

create table COMPANY_ADDRESS(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  CID BIGINT,
  AID BIGINT,
  CONSTRAINT FOREIGN KEY (CID) REFERENCES COMPANY(ID),
  CONSTRAINT FOREIGN KEY (AID) REFERENCES ADDRESS(ID)
);

create table LOAN_APPLICATION(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  USERCO_ID BIGINT,
  AMOUNT DECIMAL NOT NULL,
  TERM INTEGER NOT NULL,
  JOBS_CREATED DECIMAL,
  LOAN_PURPOSE VARCHAR(30) NOT NULL,
  CREATED TIMESTAMP NOT NULL,
  REVIEWED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  REVIEWED_BY VARCHAR(255),
  COMMENTS VARCHAR(255),
  ACCEPTED BOOLEAN,
  OFFER_APR DECIMAL,
  OFFER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  OFFER_ACCEPTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FOREIGN KEY (USERCO_ID) REFERENCES USER_COMPANY(ID)
);


# --- !Downs
drop table USER;
drop table CONTACT;
drop table ADDRESS;
drop table USER_ADDRESS;
drop table COMPANY;
drop table USER_COMPANY;
drop table COMPANY_ADDRESS;
drop table LOAN_APPLICATION;